name: Frontend CI/CD

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:
  quality-checks:
    name: Code Quality & Linting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint
      
      - name: Run Prettier check
        run: npm run format:check
      
      - name: Check for console.logs
        run: |
          if grep -r "console\.log" src/; then
            echo "Found console.log statements. Please remove them."
            exit 1
          fi
        continue-on-error: true

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: quality-checks
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_CLOUDINARY_CLOUD_NAME: ${{ secrets.VITE_CLOUDINARY_CLOUD_NAME }}
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
          retention-days: 7

  deploy-preview:
    name: Deploy Preview (Vercel)
    runs-on: ubuntu-latest
    needs: [quality-checks, build-test]
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Notify deployment
        run: echo "Vercel auto-creates preview deployment for PRs"
      
      - name: Comment PR with preview URL
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Preview deployment will be available at Vercel shortly!'
            })
        continue-on-error: true

  deploy-staging:
    name: Deploy to Staging (Vercel)
    runs-on: ubuntu-latest
    needs: [quality-checks, build-test]
    if: github.ref == 'refs/heads/development' && github.event_name == 'push'
    
    steps:
      - name: Deployment notification
        run: echo " Vercel staging deployment triggered automatically"

  deploy-production:
    name: Deploy to Production (Vercel)
    runs-on: ubuntu-latest
    needs: [quality-checks, build-test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Deployment notification
        run: echo "Vercel production deployment triggered automatically"
